/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 简单滑块匹配 - 从文件路径（无透明背景裁剪） */
export declare function simpleSlideMatchWithPath(targetImagePath: string, backgroundImagePath: string): string

/** 滑块匹配 - 从字节数组 */
export declare function slideMatchWithBuffer(targetImage: Buffer, backgroundImage: Buffer): string

/** 滑块匹配 - 从文件路径 */
export declare function slideMatchWithPath(targetImagePath: string, backgroundImagePath: string): string
