/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 改进版简单滑块匹配（无透明背景裁剪 + 自适应阈值 + 置信度验证）
 * 接受 Buffer 参数（支持 base64 解码后的 u8 数组）
 *
 * # 参数
 * - target_image: 目标图片 Buffer
 * - background_image: 背景图片 Buffer
 * - confidence_threshold: 置信度阈值，范围 0.0-1.0，默认 0.3
 */
export declare function improvedSimpleSlideMatch(targetImage: Buffer, backgroundImage: Buffer, confidenceThreshold?: number | undefined | null): SlideBBox

/** 改进版简单滑块匹配 - 从文件路径 */
export declare function improvedSimpleSlideMatchWithPath(targetImagePath: string, backgroundImagePath: string, confidenceThreshold?: number | undefined | null): SlideBBox

/**
 * 改进版滑块匹配（带透明背景裁剪 + 自适应阈值 + 置信度验证）
 * 接受 Buffer 参数（支持 base64 解码后的 u8 数组）
 *
 * # 参数
 * - target_image: 目标图片 Buffer
 * - background_image: 背景图片 Buffer
 * - confidence_threshold: 置信度阈值，范围 0.0-1.0，默认 0.3
 */
export declare function improvedSlideMatch(targetImage: Buffer, backgroundImage: Buffer, confidenceThreshold?: number | undefined | null): SlideBBox

/** 改进版滑块匹配 - 从文件路径 */
export declare function improvedSlideMatchWithPath(targetImagePath: string, backgroundImagePath: string, confidenceThreshold?: number | undefined | null): SlideBBox

/**
 * 简单滑块匹配（无透明背景裁剪）
 * 接受 Buffer 参数（支持 base64 解码后的 u8 数组）
 */
export declare function simpleSlideMatch(targetImage: Buffer, backgroundImage: Buffer): SlideBBox

export interface SlideBBox {
  targetX: number
  targetY: number
  x1: number
  y1: number
  x2: number
  y2: number
}

/**
 * 滑块匹配（带透明背景裁剪）
 * 接受 Buffer 参数（支持 base64 解码后的 u8 数组）
 */
export declare function slideMatch(targetImage: Buffer, backgroundImage: Buffer): SlideBBox
